### PR TITLE
📦 feat(retext-german): add new package for parsing German natural language

### PR DESCRIPTION
**Pull request by nyxb**
### Initial checklist

*   [ x] I read the support docs 
*   [x ] I read the contributing guide 
*   [ x] I agree to follow the code of conduct 
*   [x ] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x ] If applicable, I’ve added docs and tests

### Description of changes

Hi I created this because I need it for a project and thought so you can extend the whole thing with a language. 😊

I also had to create a german-parser for it which I also just adapted from yours. I would also like to give you the repository if you want. you can find it here: https://github.com/nyxb/parse-german. It takes into account the german spelling as well as umlauts etc.

🔧 chore(retext-german): add .npmrc and tsconfig.json for package configuration

📝 docs(retext-german): add readme.md for package documentation

🎉 init(retext-german): create index.js and lib/index.js for initial package setup

🔧 chore(retext-german): add package.json for package metadata and dependencies

### CODE REVIEW

**Comment by nyxb** [comment]
Strange that the node tests do not run I do not have these errors locally.
image

i only see this one: 
```
yarn run v1.22.19
$ npm run build && npm run format && npm run test-coverage

> build
> tsc --build --clean && tsc --build && type-coverage

test.js:135:14 - error TS2367: This comparison appears to be unintentional because the types '"SourceNode" | "WhiteSpaceNode" | "SymbolNode" | "PunctuationNode" | "WordNode"' and '"EmoticonNode"' have no overlap.

135       assert(emoji.type === 'EmoticonNode')
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wooorm** [comment]
Hi Dennis, thanks for your work and your patience!

> I would also like to give you the repository if you want.

No, thank you. Seems like extra work that I cannot do (I am not a native german speakers), with no benefit: it’s open source, anyone can maintain anything.

---

It looks like you copy/pasted a folder in there. That’s a good start, but doesn’t make everything workable.
You need to add it as a workspace in the root package.json: https://github.com/retextjs/retext/blob/0d7c1681adc475ccfe3f607d20d272f4e65fca02/package.json#L12.
Then you run `npm install` and `npm test` and such from there.

You are also currently getting type errors. I assume because `index.d.ts` is not published in `parse-german`. Can you also at least publish a `0.1.0` there? That way, semver can work. At `0.0.1` semver does not work.

For your new package `retext-german` here, you can start with `0.0.0`. I will do the publishing and update the versions for you.

Particularly the `npm test` I mentioned earlier is important to run: that formats everything. Looking at the readme, it’s not formatted according to this project’s style.

As for your error here: you are using yarn. Don’t use yarn, we use npm. From the root of the project run `npm install` and then `npm test` and such.

**Comment by nyxb** [comment]
Ok will do it

**Comment by wooorm** [comment]
Thanks for the PR. Closing for now as this cannot land currently and there seems to be no activity.

I recommend just publishing and maintaining this yourself! I don’t need to do all the work. It’s open source. Others can do work too!

**Pull request closed without merging**
